# Generated by Django 4.1 on 2022-08-12 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repository_name', models.CharField(max_length=50)),
                ('owner_name', models.CharField(max_length=50)),
                ('contract_id', models.CharField(max_length=10)),
                ('commit_id', models.CharField(max_length=50)),
                ('expired', models.BooleanField()),
                ('badge', models.CharField(max_length=50)),
            ],
        ),
    ]
