# Generated by Django 4.1 on 2022-08-20 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twins', '0004_application_file_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='file_path',
            field=models.CharField(max_length=64),
        ),
    ]
